### BRS LogicX: statement lines of a Bank Account, in statement order.
POST {{baseUrl}}/api/v2/method/frappe.client.get_list
Authorization: token {{token}}
Content-Type: application/json

{
	"doctype": "BRS LogicX",
	"filters": [
		[ "bank_account", "=", "HDFC - 50100123456789" ]
	],
	"order_by": "date asc, day_order asc",
	"fields": [
		"name",
		"bank_account",
		"date",
		"day_order",
		"description",
		"reference_no",
		"withdrawal",
		"deposit",
		"balance"
	]
}



### Read BRS LogicX by ID.

GET {{baseUrl}}/api/v2/document/BRS LogicX/BRS1
Authorization: token {{token}}



### Create: one statement line.
	# "date" is optional: it defaults to the server's today.
	# "day_order" is set by the server: 1, 2, 3... within the same Bank Account and Date.
	# Send either "withdrawal" or "deposit", not both: both empty or both set is rejected.
POST {{baseUrl}}/api/v2/document/BRS LogicX
Authorization: token {{token}}
Content-Type: application/json

{
  "bank_account": "HDFC - 50100123456789",
  "date": "2026-09-24",
  "description": "NEFT from customer",
  "reference_no": "N267123456789",
  "deposit": 25000,
  "balance": 125000
}


###
